# action.yaml
name: 'Get LemonTreeAutomation'
description: 'This action downloads LieberLieber LemonTree.Automation for Sparx Systems Enterprise Architect on a build runner!'
inputs:
  License:
    description: 'A string containing the license information'
    required: false
    default: ''
outputs:
  LemonTreeAutomationExecutable:
    description: 'Path to the Executable'
    value: "${{steps.DownloadLTA.outputs.LemonTreeAutomationExecutable}}"
runs:
  using: 'composite'
  steps:
   - name: Run getLTA.ps1 script with license from secret
  run: |
    Set-ExecutionPolicy RemoteSigned -Scope Process -Force

    # Use the GitHub secret to pass the license info
    .\getLTA.ps1 -License "${{ secrets.LICENSE_KEY }}" -RunnerOs 'Windows'
