name: Run getLTA.ps1

on:
  push:
    branches:
      - main  # You can specify other branches if needed
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest  # Change to linux-latest for Linux runners or other OS if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run getLTA.ps1 script
      run: |
        # Ensure script execution policy is set to allow script running
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force

        # Run the getLTA.ps1 script with parameters
        .\getLTA.ps1 
